### PR TITLE
Google test module w some tests 

### PR DESCRIPTION
**Pull request by saneck2150**

### CODE REVIEW

**Comment by gavv** [comment]
@saneck2150 Hi, please don't recreate same PRs again and again, instead you can always force-push to the same PR.

**Comment by saneck2150** [comment]
ok, sorry. But idk, for some reason i can make my local project in vscode. But it is failing all the git tests

**Comment by saneck2150** [comment]
I'm very sorry for the Commits spam. This is my first time trying to support open source external projects.

**Comment by gavv** [comment]
You specified wrong value for gtest SOURCE_DIR (it's not in CMAKE_BINARY_DIR).

Also you can't use find_package. find_package works at configuration time (when cmake is running), but ExternalProject_Add works at build time (when make is running). So find_package won't be able to find anything because gtest package is not generated yet. (It may incorrectly find system-wide installed gtest, if it's present, but we don't want this).

That's why we don't use find_package() for other deps and instead add include dirs and libs manually.

To avoid commit spam, you can debug CI in your fork (in branch different from PR).

**Comment by saneck2150** [comment]
Ok, thank you very much

**Pull request closed without merging**
