### PR TITLE
Result ploting

### PR DESCRIPTION
**Pull request by RandomJanis**
Implementing #47
Added measurement result curves to plot. Since signals and results have different scales, added them on seperate Y axes. It is not perfect: in losses mode there are  3 different Y dimensions, but only 2 Y axis available.
Also added checkboxes to gui to show or hide curves accordingly.

### CODE REVIEW

**Comment by gavv** [comment]
Hi, thanks a lot for PR!

Just tested it, looks nice. Here are a few suggestions / questions:

1. What do you think about moving measurements to separate plots? For example, in latency modes (latency_corr and latency_step) we can show three plots:

   * input + output
   * hw_sw latency
   * hw + hw_avg latencies

   Rationale:

    * Currently, it's hard to monitor jitter in `hw` and `hw_sw` latencies because this jitter is small compared to distance between `hw` and `hw_sw` on plot (jitter is typically withing few milliseconds, and distance can be tens of milliseconds). With separate plots each will have separate scale.

    * Currently, if `hw` or `hw_sw` happen to display in the middle of plot, it's a bit messed up with input / output.

2. To avoid duplication, I think we could inline these checkboxes:

   
   image


   into legend:

   image

   e.g. we can show checkbox before each label.

   As for the grid checkbox, I think we can remove it at all and just always show grid.

3. Since measurement reports are quite scattered, it would be useful to show points on plot, to distinguish between real data and interpolation.

   Example:

   image

4. Maybe latency plot will look nicer if we also fill color under the line.

   Example:

   image

**Comment by RandomJanis** [comment]
As suggested:
- split results in multiple plots
- added brush/fill for result plots
- added marker dots

As for checkboxes, with 2 curves per plot, I think they are not needed.
Also changed plot background color to default, in my opinion white plot didn't fit in dark color scheme.
Cursor trackers now show positions on plots. If needed I can change it back to label somewhere (I'm not sure where).
image

**Comment by gavv** [comment]
Looks awesome, thank you so much!

Two follow-up commits:

* 7ed6e867b597b29e35dd7b0b7f2e1c7fb0663a73 - in fresh main branch, signal-estimator switched from monotonic to wallclock timestamps in csv dumps (which we parse in GUI), this commit updates plots accordingly and also switches units to milliseconds for convenience

* ca406df421374e8a472658e4faa193f3f80be441 - there was a segfault in QwtPlotCurve destructor (when we exit app) cause by using same symbol for several plots; this commit fixes it

**Comment by gavv** [comment]
I created a follow-up issue, partially related to this PR: #66

Also somewhat related: #67, #68 (they become relevant since we now display measurement plots).

**Comment by gavv** [comment]
One more follow-up issue: #69

**Comment by gavv** [comment]
Updated colors a bit:

image

I used colors different from input & output signals to make it clear that this plot show different data. (I used https://coolors.co)

@RandomJanis Could you please take a look whether the new colors look fine on dark theme?

**Comment by gavv** [comment]
One more issue: #70

**Comment by RandomJanis** [comment]
image
Except that hardware and average hardware latency looks the same, looks ok.

**Pull request merged**
