### PR TITLE
Use spdlog for logging

### LINKED ISSUE #38: Switch to spdlog
- [x] Add [spdlog](https://github.com/gabime/spdlog) submodule to `3rdparty/` dir.
- [x] Add spdlog to `cmake/ThirdParty.cmake`.
- [x] Switch macros `core/Log.hpp` from fprintf() to spdlog.
- [x] Rework all invocations of `se_log_*()` macros to use `{fmt}` instead of printf format strings.
- [x] Initialize spdlog at program start, use asynchronous logger.

### PR DESCRIPTION
**Pull request by aadit-n3rdy**
Resolves #38 

spdlog is linked against base_objects in CMakeLists.txt, since it is required by both CLI and GUI. Asynchronous logging has been used.

### CODE REVIEW

**Comment by aadit-n3rdy** [comment]
Hey, I'm not able to get arm32 and arm64 build working, it says that the package alsa is not found. I haven't touched any of the sections of the CMake files involving alsa, or any other dependency. Is there something I'm doing wrong?

**Comment by gavv** [comment]
Thanks for PR! Will review in upcoming days.

> Hey, I'm not able to get arm32 and arm64 build working, it says that the package alsa is not found. I haven't touched any of the sections of the CMake files involving alsa, or any other dependency. Is there something I'm doing wrong?

I think this can be caused by using add_subdirectory(). I usually try to avoid it because it can easily create a mess, since projects may modify global settings in incompatible way.

Anyway, in ThirdParty.cmake we use ExternalProject_Add to build all other dependencies, so please use it for spdlog as well, and we'll see if it helps.

---

Also, a few nitpicks after quick look at the code:

* I think we don't need to add "\n" to format string with spdlog.
* In places where there were casts for logged integer argument, like `se_log_info("selected_period_size: %u samples", (unsigned)*period_size)`, we don't need these casts anymore because `{fmt}` will automatically detect argument type
* please use `<>` for including spdlog (we use `""` only for our own headers)

**Comment by aadit-n3rdy** [comment]
Thanks for the pointer about add_subdirectory(), spdlog is now built using ExternalDependency_add().

 I've also made the other changes mentioned in the previous comment.

**Comment by gavv** [comment]
Thanks, LGTM!

I've pushed a small follow-up commit: aad5280d86fb56fb7e5c7361eff7173f9b073989

* switched to synchronous logger; after looking at the code more closely, it appeared that we don't use logging in real-time, only during initialization, so async logger is not really needed; on the other hand, when we use async logger, our messages are messed with ALSA (libasound) messages

* changed pattern and colors

* change log levels of some messages

**Pull request merged**
